### ISSUE TITLE
Build app with unused Crayons components

### ISSUE THREAD

**Issue by shravan-balasubramanian** [freshworks-developers/crayons-samples#3]
Build an app with fair use case to demonstrate unused components' use

**Comment by Saif-Shines** [comment]
@shravan-balasubramanian  - By any chance do you have a use case on your mind that can help demonstrate crayons better?

**Comment by shravan-balasubramanian** [comment]
Any full-page app that has a rich form. Using crayons v3 extensively! @Saif-Shines

**Comment by Saif-Shines** [comment]
I tried to use more components in the full page in the following pull request: #4

**Comment by Saif-Shines** [comment]
@shravan-balasubramanian  - When you have some time, review the merged branch for Freshdesk and share your feedback. :)
